name: Readout Tool Build
on: 
  push:
    paths:
    - 'rust/readaout/**'
    - 'lib/include/**'
#  workflow_dispatch:  

env:
  CARGO_TERM_COLOR: always
  SOLUTION_FILE_PATH: .\rust\readout

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env: 
      X86_OUTPUT_DIR_NAME: Build_x86
      X64_OUTPUT_DIR_NAME: Build_x64
      X86_OUTPUT_DIR: .\Build_x86\release\
      X64_OUTPUT_DIR: .\Build_x64\release\
      X86_EXE_REPO_DIR: .\rust\bin\x86\
      X64_EXE_REPO_DIR: .\rust\bin\x64\
      X86_BINDINGS_REPO_DIR: .\rust\readout\src\bindings\x86\
      X64_BINDINGS_REPO_DIR: .\rust\readout\src\bindings\x64\
      X86_EXE_NAME: xhptdc8_readout.exe
      X64_EXE_NAME: xhptdc8_readout.exe
      X86_EXE_REPO_NAME: xhptdc8_readout.exe
      X64_EXE_REPO_NAME: xhptdc8_readout_64.exe
      X86_BINDINGS_RS_NAME: bindings.rs
      X64_BINDINGS_RS_NAME: bindings.rs
      X86_BINDINGS_RS_REPO_NAME: bindings.rs
      X64_BINDINGS_RS_REPO_NAME: bindings_64.rs
      X86_LLVM_BIN_PATH: C:\Program Files (x86)\LLVM\bin
      COMMIT_MSG: 'Internal build due to code change' 
        
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Install LLVM and Clang, x64
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
        directory: ${{ runner.temp }}/llvm    
        
#    Uncomment the following item if you need to display more information
#    - name: Display Environment Settings
#      run: |
#        rustup show
         
    # Assuming that 'stable-x86_64-pc-windows-msvc' is default
    - name: Build x64 Release
      run: | 
        clang --version
        SET LIBCLANG_PATH=%LD_LIBRARY_PATH:~0,-1%
        cd ${{env.SOLUTION_FILE_PATH}}
        cargo build --target-dir=${{env.X64_OUTPUT_DIR_NAME}} --release --verbose

    # Copy EXE 
    - name: Copy x64 Files to Repository
      run: |
        copy ${{env.SOLUTION_FILE_PATH}}\${{env.X64_OUTPUT_DIR}}${{env.X64_EXE_NAME}} ${{env.X64_EXE_REPO_DIR}}${{env.X64_EXE_REPO_NAME}}
        
    - name: Commit x64 EXE
      uses: EndBug/add-and-commit@v7.0.0
      with:
          author_name: Internal Workflow Action
          message: ${{env.COMMIT_MSG}}
          add: ${{env.X64_EXE_REPO_DIR}}${{env.X64_EXE_REPO_NAME}} --force

    - name: Commit x64 bindings
      uses: EndBug/add-and-commit@v7.0.0
      with:
          author_name: Internal Workflow Action
          message: ${{env.COMMIT_MSG}}
          add: ${{env.X64_BINDINGS_REPO_DIR}}${{env.X64_BINDINGS_RS_REPO_NAME}} --force

    - name: Install Target i686 and Set As Default for rustup
      run: |
        rustup show
        rustup install stable-i686-pc-windows-msvc
        rustup target add stable-i686-pc-windows-msvc
        rustup default stable-i686-pc-windows-msvc
        rustup show

    - name: Install LLVM Win32
      run: |
        curl https://prereleases.llvm.org/win-snapshots/LLVM-12.0.0-6923b0a7-win32.exe -o C:\Temp\LLVM_Win32.exe
        C:\Temp\LLVM_Win32.exe /S

    # ~20%: remove "D:\a\_temp\llvm\bin" from LLVM x64 Installation
    - name: Build x86 Release
      run: | 
        set LIBCLANG_PATH=${{env.X86_LLVM_BIN_PATH}}
        set PATH=%PATH:~20%
        set PATH=%PATH%;${{env.X86_LLVM_BIN_PATH}}
        cargo --version
        cd ${{env.SOLUTION_FILE_PATH}}
        cargo build --target-dir=${{env.X86_OUTPUT_DIR_NAME}} --release --verbose

    # Copy EXE 
    - name: Copy x86 Files to Repository
      run: |
        copy ${{env.SOLUTION_FILE_PATH}}\${{env.X86_OUTPUT_DIR}}${{env.X86_EXE_NAME}} ${{env.X86_EXE_REPO_DIR}}${{env.X86_EXE_REPO_NAME}}
        
    - name: Commit x86 EXE
      uses: EndBug/add-and-commit@v7.0.0
      with:
          author_name: Internal Workflow Action
          message: ${{env.COMMIT_MSG}}
          add: ${{env.X86_EXE_REPO_DIR}}${{env.X86_EXE_REPO_NAME}} --force

    - name: Commit x86 bindings
      uses: EndBug/add-and-commit@v7.0.0
      with:
          author_name: Internal Workflow Action
          message: ${{env.COMMIT_MSG}}
          add: ${{env.X86_BINDINGS_REPO_DIR}}${{env.X86_BINDINGS_RS_REPO_NAME}} --force
