name: Readout Tool Build
on: 
  push:
    paths:
    - 'rust/readaout/**'
    - 'lib/include/**'
  workflow_dispatch:  

env:
  CARGO_TERM_COLOR: always
  SOLUTION_FILE_PATH: .\rust\readout

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env: 
      X86_OUTPUT: Build_x86
      X64_OUTPUT: Build_x64
      COMMIT_MSG: 'Internal build due to Dummy-Library code change' 
        
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Install LLVM and Clang, x64
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
        directory: ${{ runner.temp }}/llvm    
        
#    Uncomment the following item if you need to display more information
#    - name: Display Environment Settings
#      run: |
#        rustup show
         
    # Assuming that 'stable-x86_64-pc-windows-msvc' is default
    - name: Build x64 Release
      run: | 
        clang --version
        SET LIBCLANG_PATH=%LD_LIBRARY_PATH:~0,-1%
        cd ${{env.SOLUTION_FILE_PATH}}
        cargo build --target-dir=${{env.X64_OUTPUT}} --release --verbose

    - name: Install Target i686 and Set As Default for rustup
      run: |
        rustup show
        rustup install stable-i686-pc-windows-msvc
        rustup target add stable-i686-pc-windows-msvc
        rustup default stable-i686-pc-windows-msvc
        rustup show

    - name: Install LLVM Win32
      run: |
        curl https://prereleases.llvm.org/win-snapshots/LLVM-12.0.0-6923b0a7-win32.exe -o C:\Temp\LLVM_Win32.exe
        C:\Temp\LLVM_Win32.exe /S

    - name: Build x86 Release
      run: | 
        set LIBCLANG_PATH=C:\Program Files (x86)\LLVM\bin
        set PATH=%PATH:~20%
        set PATH=%PATH%;C:\Program Files (x86)\LLVM\bin
        cargo --version
        cd ${{env.SOLUTION_FILE_PATH}}
        cargo build --target-dir=${{env.X86_OUTPUT}} --release --verbose
